### ISSUE TITLE
support chatgpt 4

### ISSUE THREAD

**Issue by BenCherif** [AsyncWeb/strapi-chatgpt#6]
can you make this plugin support chatgpt 4 ?

**Comment by theCompanyDream** [comment]
Bruh I wouldn't hold my breath for this I tried to fork the repository to see if I could work on it. There is no instructions on how to even build strapi plugins so I can test it.

**Comment by theCompanyDream** [comment]
I've been working on this weekend because I couldn't get this working for my client. I have gotten this working for myself and am working on getting this working for dall-e. So you can create pictures using dall-e but as is you can actually use GPT-4 and GPT-3.5. If you're curious you can follow my progress.

https://github.com/theCompanyDream/strapi-chatgpt/pull/1

**Comment by BenCherif** [comment]
Thanks bro for your efforts
